In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import matplotlib.pyplot as plt
import matplotlib.cm as cm

import numpy as np

import sys
sys.path.append("..")
from encoder_learning_benchmarks.common import numerical_jacobian
from encoder_learning_benchmarks.mahalanobis_distance import MahalanobisDistance

np.set_printoptions(precision=4, suppress=True)

In [3]:
x = [[0, 1], [1, 1], [1, 0], [-1, 0]]
y = [[3, 0], [2, 0], [0, 1], [1, 2], [-1, 2]]
theta = [[1, 0.1, 2], [0, 0, 0], [1, 0, -1], [0, -1, 0], [0, 1, 2]]
d = MahalanobisDistance(2)

In [4]:
for i in range(len(y)):
    print(-d.jacobian(x, y, theta)[0][:, i:(i+1), :])

[[[33.4612 22.1766]]

 [[18.6831 11.3034]]

 [[29.5562 21.7463]]

 [[59.1124 43.4925]]]
[[[ 4. -2.]]

 [[ 2. -2.]]

 [[ 2. -0.]]

 [[ 6. -0.]]]
[[[ -0.      -0.    ]]

 [[-14.7781   5.4366]]

 [[-20.2147   9.4366]]

 [[  9.3415  -1.4366]]]
[[[ 2. -0.]]

 [[-0. -0.]]

 [[-0. -0.]]

 [[ 4. -0.]]]
[[[ 2.     18.7781]]

 [[-0.     14.7781]]

 [[ 4.     37.5562]]

 [[ 8.     45.5562]]]


In [5]:
for i in range(len(y)):
    f = lambda y: d(x, y, theta[i])
    print(numerical_jacobian(f, y[i]))

[[[33.4612 22.1766]]

 [[18.6831 11.3034]]

 [[29.5562 21.7463]]

 [[59.1124 43.4925]]]
[[[ 4. -2.]]

 [[ 2. -2.]]

 [[ 2.  0.]]

 [[ 6.  0.]]]
[[[  0.       0.    ]]

 [[-14.7781   5.4366]]

 [[-20.2147   9.4366]]

 [[  9.3415  -1.4366]]]
[[[2. 0.]]

 [[0. 0.]]

 [[0. 0.]]

 [[4. 0.]]]
[[[ 2.     18.7781]]

 [[ 0.     14.7781]]

 [[ 4.     37.5562]]

 [[ 8.     45.5562]]]


In [6]:
for i in range(len(y)):
    print(d.jacobian(x, y, theta)[2][:, i:(i+1), :])

[[[100.3836   2.4428 -12.3097]]

 [[ 37.3662   2.4428  -6.8731]]

 [[ 59.1124   0.      -0.    ]]

 [[236.4498   0.      -0.    ]]]
[[[ 8.  2. -4.]]

 [[ 2.  2. -2.]]

 [[ 2.  0. -0.]]

 [[18.  0. -0.]]]
[[[ 0.      0.      0.    ]]

 [[14.7781  0.      0.    ]]

 [[20.2147  2.     -7.4366]]

 [[ 9.3415  2.      3.4366]]]
[[[ 2. -0.  2.]]

 [[ 0. -0. -0.]]

 [[ 0. -0. -0.]]

 [[ 8. -0.  8.]]]
[[[-2.     14.7781  2.    ]]

 [[ 0.     14.7781 -0.    ]]

 [[-8.     59.1124  8.    ]]

 [[-0.     59.1124 16.    ]]]


In [7]:
for i in range(len(y)):
    f = lambda theta: d(x, y[i], theta)
    print(numerical_jacobian(f, theta[i]))

[[[100.3836   2.4428 -12.3097]]

 [[ 37.3662   2.4428  -6.8731]]

 [[ 59.1124   0.       0.    ]]

 [[236.4498   0.       0.    ]]]
[[[ 8.  2. -4.]]

 [[ 2.  2. -2.]]

 [[ 2.  0.  0.]]

 [[18.  0.  0.]]]
[[[ 0.      0.      0.    ]]

 [[14.7781  0.      0.    ]]

 [[20.2147  2.     -7.4366]]

 [[ 9.3415  2.      3.4366]]]
[[[ 2.  0.  2.]]

 [[ 0. -0.  0.]]

 [[ 0. -0.  0.]]

 [[ 8.  0.  8.]]]
[[[-2.     14.7781  2.    ]]

 [[ 0.     14.7781  0.    ]]

 [[-8.     59.1124  8.    ]]

 [[ 0.     59.1124 16.    ]]]
